### ISSUE TITLE
To-do List

### ISSUE THREAD

**Issue by ss7886** [jzhang512/-COS333-Philly-Community-Wireless-Webapp#132]
Map:
- [x] - Close review bug
- [x] - Check mobile design (go for minimum functionality, not design)
- [ ] - Redesign Hotspot info (no reviews, don't show ul/dl speed when no info)
- [x] - Redesign Filters (no scroll, fix arrow for close)
- [x] - Add pin at location (John)
- [x] - Add sort by rating (Sam)
    - [x] - Add database function to get all scores
    - [x] - Add API endpoint to get scores
    - [x] - Calculate average score on back end
    - [x] - Add sort by score functionality
- [ ] - Validate frontend input for reviews (john)
     - [ ] - Add character limit for reviews (john)
- [ ] - Fix db where failure does sys.exit
- [x] - Fix hotspot list ordering when "sort by" and filter applied

Admin:
- [ ] - Redesign unauthorized admin page
- [ ] - Redesign add admin page
- [ ] - Validate input for Update hotspots page
- [x] - Add Privacy tags to Update hotspots page
- [ ] - Success/Error messages (john)
    - [ ] - Update Hotspots page (john)
    - [ ] - Pending Reviews (john)
- [ ] - Add/Remove Tags
    - [ ] - Database function
    - [ ] - API Endpoint
    - [ ] - Design Admin page
    - [ ] - Connect to backend
- [ ] - Import/Exporting data
    - [ ] - Add Admin page for managing data
    - [ ] - Add functionality to export data to .csv
    - [ ] - Add functionality to import data from .csv
- [ ] - Approve user-suggested hotspots
    - [ ] - Add Admin page for managing user-suggested hotspots
    - [ ] - Add form on map for suggesting hotspots
    - [ ] - Add approval system similar to pending reviews page
