### ISSUE TITLE
Front-end/Back-end todo for prototype

### ISSUE THREAD

**Issue by ss7886** [jzhang512/-COS333-Philly-Community-Wireless-Webapp#7]
Basically all of the communication between the front and backends will be via HTTP requests. When the user first accesses the site the backend will serve the html page to be displayed. Then right away the front end needs to send a request to get all of the pin data which the backend will serve as a JSON object so that it can be displayed on the map. Then every time a user clicks on a pin the front end needs to send another request to get the reviews for that pin which the backend will also serve as a JSON object.

- [x] Replace `templates/index.html` with `index.html`.
- [x] Write JS function to make GET request to `/api/hotspots` to be called when site is initially loaded.
- [x] Write JS function to make GET request to `/api/reviews?pin_id=...` to be called when a pin is clicked.
- [x] Update Flask code to handle HTTP requests to `/api/hotspots` and `/api/reviews`.
- [x] Update DB code to get reviews.

@john-van-horn @jzhang512
